### PR TITLE
Changes to support running on the latest ACA-Py

### PR DESCRIPTION
**Pull request by farskipper**

### CODE REVIEW

**Review by dbluhm — CHANGES_REQUESTED** [review]
Looks like we need to update the `requirements.txt` file to point to the most recent commit of ACA-Py that we're targetting.

**Comment by JamesKEbert** [comment]
As a note--I _think_ I was able to point to a release tag vs a commit hash as well, if you're looking to target a specific release.

**Comment by dbluhm** [comment]
> As a note--I _think_ I was able to point to a release tag vs a commit hash as well, if you're looking to target a specific release.

Ah, thanks for the pointer (pun intended lol); for this one we will need to target a specific commit of main since the feature we're building off isn't released yet.

**Comment by JamesKEbert** [comment]
Lol no stress, figured it could be helpful in case you weren't aware!

**Review by dbluhm — APPROVED** [review]

**Pull request merged**
